### ISSUE TITLE
Hide spoilers in TITR videos no longer hides comment count on main page list

### ISSUE THREAD

**Issue by DigTheDoug** [lrkissling/giant-bomb-qol#11]
This is the Run videos on the main page feed show the comment count, though it is hidden on other pages (like the TIRT show page). It looks as thought the main feed selectors have probably changed and the current comment element selector in the extension is no longer accurate.

**Comment by lrkissling** [comment]
Thanks for pointing this out, I will try and fix this over the weekend.
