### ISSUE TITLE
[Enhancement Suggestion] Hiding new unwatched TITR episodes?

### ISSUE THREAD

**Issue by DigTheDoug** [lrkissling/giant-bomb-qol#13]
Not sure that this is possible with the information available through the api, but it'd be great as an added option to be able to hide new This is the Run shows from showing on the main feed if you have any that are unwatched. If I am a few days or week behind I do 'get spoiled' by seeing new episodes pop up on the main feed. Of course, with this I suppose you'd also need to hide those videos from the show page as well, until you 'get to them', so that definitely complicates things. 

So, not sure if it's possible, but something I definitely see the need for. The multiple game runs in TITR complicate it, otherwise you might be able to scan the 'get-saved-time` end point to find out the last episode the user has watched and hide all future ones, thought that could also be potentially heavy from the amount of api requests. Maybe it only works to a limit of being n episodes behind?

Anyways, just something that I was thinking of. Any thoughts on the matter?

**Comment by lrkissling** [comment]
That's certainly something I can look into, thanks for the suggestion. I'm a little hesitant to do any major work right now since the site redesign seems to be right around the corner, and I imagine it is gonna break everything. But I can see if this would be easily implemented.

**Comment by DigTheDoug** [comment]
Ahh yeah, that's a really good call about the redesign, makes total sense to hold off anything until then.

**Comment by lrkissling** [comment]
The site redesign makes identifying which videos are This Is The Run videos on the main page or the videos feed pretty much impossible. Since video titles no longer include the name of their respective series, TITR videos unfortunately cannot be picked out.
