### ISSUE TITLE
Validation for API key field

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#20]
As a user, it is tough to know if I have properly added my API key to the extension's options page. Visual validation (e.g. red border vs green border) would help me know if I have entered a valid key.

**Comment by kmausolf** [comment]
Support for this was added in my latest pull request, but only to the popup.  I will add the same support to the options page.

**Comment by lrkissling** [comment]
Thanks for your work on this, kmausolf. I'm hoping to check out the pull
request on Thursday or Friday.

**Comment by kmausolf** [comment]
No problem!  Let me know if there's anything I can add (or simplify)!

**Comment by kmausolf** [comment]
#32 closes this issue.

**Comment by lrkissling** [comment]
@kmausolf what's your giant bomb username again? I would like to thank you in the forum post for your work on this.

**Comment by kmausolf** [comment]
No need to do that, but I'm Darling on the site!

**Comment by kmausolf** [comment]
Most of all, I would like the ability to tag myself on issues so I can communicate what I'm working on better.

**Comment by lrkissling** [comment]
Yeah I was hoping to tag you on this issue as well. Unfortunately, I can't do that without making you a collaborator with full push access to the repository. Looking into it, I could create an open source team github account (which is still free) and transfer this project to it, where I could then get more granular account access controls. I won't have time to figure out all that until after my vacation, though.
