### ISSUE TITLE
Allow submission of API key on toolbar dropdown

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#21]
Rather than directing users to the addon's options page when they have not entered an API key, the toolbar dropdown should allow the user to enter their API key right there.

**Comment by kmausolf** [comment]
Working on this one.

**Comment by kmausolf** [comment]
As part of this, may I add a live stream notification toggle to the popup?

**Comment by lrkissling** [comment]
Yeah, go ahead!

**Comment by kmausolf** [comment]
Nearing testing phase.  My next day off is Monday, so I'll probably get things going then.

**Comment by lrkissling** [comment]
Sounds good. I should probably be able to check stuff out on Tuesday
evening if it's available by then.

**Comment by kmausolf** [comment]
Alrighty, I pushed what I've been working on to my fork on the api_key_popup branch.  It's currently untested, so please do not merge.  I'll begin testing shortly.  https://github.com/kmausolf/giant-bomb-qol.git

**Comment by kmausolf** [comment]
Basic functionality is complete.  All that remains is to polish up the feature.

**Comment by kmausolf** [comment]
Stream notification button is now working consistently.  My pull request addresses this issue.

**Comment by kmausolf** [comment]
This feature has been redesigned to automatically check the validity of the API key upon submission and highlight the input box green for success and red for failure.  The updated pull request should solve this.

**Comment by kmausolf** [comment]
#32 closes this issue.
