### ISSUE TITLE
jackyt emote

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#30]
`:jackyt`
`https://static.giantbomb.com/uploads/original/0/1992/3022414-untitled-1.png`

**Comment by lrkissling** [comment]
also, the bakalar emote...
`:bakalar`
`https://static.giantbomb.com/uploads/original/0/1992/3022236-bakalar.png'

**Comment by kmausolf** [comment]
My pull request addresses this concern.

**Comment by lrkissling** [comment]
Thanks!
