### ISSUE TITLE
Emote emote emote

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#39]
`:funfactor`
https://static.giantbomb.com/uploads/original/0/1992/3080605-untitled-1.png

**Comment by lrkissling** [comment]
`:jgps`
https://static.giantbomb.com/uploads/original/36/366200/3080765-jgps.png

**Comment by lrkissling** [comment]
`:pax`
https://static.giantbomb.com/uploads/original/0/1992/3069935-2893216-qqbptkrq+copy.png

**Comment by lrkissling** [comment]
`:pnc`
https://static.giantbomb.com/uploads/original/36/366200/3081110-pnc.png

**Comment by kmausolf** [comment]
I'll pick this up over the weekend.

**Comment by kmausolf** [comment]
Tomorrow might be a better day.  My wife had a dental emergency this weekend, so I've been tending to her.

**Comment by lrkissling** [comment]
`:toosweet`
https://static.giantbomb.com/uploads/original/0/1992/3082529-untitled-1.png

`:vinnbot`
https://static.giantbomb.com/uploads/original/36/366200/3082846-vinnbot.png

**Comment by lrkissling** [comment]
`:tmoves`
https://static.giantbomb.com/uploads/original/36/366200/3082787-tmoves.png
