### ISSUE TITLE
QLCrew Links For Poll Options

### ISSUE THREAD

**Issue by kmausolf** [lrkissling/giant-bomb-qol#42]
The user should be able to quickly inform themselves on the content of a poll option.  Often times, users accidentally vote for a video that they've seen recently, not recognizing the title or date.  This may improve the quality of the Giant Bomb Infinite experience

**Comment by lrkissling** [comment]
This is a great idea! It seems like the quickest way of doing this is to form a QLCrew search url on the poll option, minus the runtime and date info. So "Quick Look: Kingdoms of Amalur: Reckoning (58:08 - 2012)" turns into [https://qlcrew.com/?q=Quick+Look%3A+Kingdoms+of+Amalur%3A+Reckoning](https://qlcrew.com/?q=Quick+Look%3A+Kingdoms+of+Amalur%3A+Reckoning). I'm not confident this will work for every video that appears in a GB Infinite poll, but it should work for most. If you have another approach in mind, I'm all ears.

We should make the linking work regardless of whether a poll is active or expired, just so this isn't a total pain to develop and test. I'm not sure whether the actual text of the poll option should be the link...

> [Quick Look: Kingdoms of Amalur: Reckoning (58:08 - 2012)](https://qlcrew.com/?q=Quick+Look%3A+Kingdoms+of+Amalur%3A+Reckoning)

Or if we should include the link afterwards...

> Quick Look: Kingdoms of Amalur: Reckoning (58:08 - 2012)[QL Crew](https://qlcrew.com/?q=Quick+Look%3A+Kingdoms+of+Amalur%3A+Reckoning)

Any thoughts or other suggestions?

**Comment by lrkissling** [comment]
Looking at the mouseover behavior of an active poll, where you can click anywhere on a poll option to select it, I am leaning towards the second option mentioned above. We need to make it clear that you can view the QL Crew info without accidentally voting for the poll option.

**Comment by lrkissling** [comment]
I'm gonna take this one on.

**Comment by lrkissling** [comment]
Resolved with commit 5d716f5d320e964ab362c0793a224121f3205312

**Comment by lrkissling** [comment]
`
.poll-choices__item.qol-without-after::after{
  content: "";
}
`

`
$("#js-poll-answer-container").on("hover", ".qol-infobutton", function() {
  $(this).parent().addClass("qol-without-after");
}, function() {
  $(this).parent().removeClass("qol-without-after");
}
`

**Comment by lrkissling** [comment]
Actually completed with commit e118370c1b32cb9cd7d20ec01f80ca46b3db27de
