### ISSUE TITLE
actual emotes that will actually be added

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#43]
`:puggy`
https://static.giantbomb.com/uploads/original/36/366200/3086801-puggy.png

**Comment by lrkissling** [comment]
`:fadetoblack`
https://static.giantbomb.com/uploads/original/0/1992/3088006-ezgif-4-50c74dfa62a5.gif

**Comment by lrkissling** [comment]
`:ghosty`
https://static.giantbomb.com/uploads/original/36/366200/3086598-ghosty.png

**Comment by kmausolf** [comment]
:srs
https://static.giantbomb.com/uploads/original/36/366200/3089051-srs.png

**Comment by lrkissling** [comment]
`:inca`
https://static.giantbomb.com/uploads/original/36/366200/3090685-inca.gif

**Comment by lrkissling** [comment]
`:valex`
https://static.giantbomb.com/uploads/original/36/366200/3090686-valex.gif

**Comment by lrkissling** [comment]
Added in v2.6
