### ISSUE TITLE
Pull Requests Welcome?

### ISSUE THREAD

**Issue by da-moo** [lrkissling/giant-bomb-qol#44]
Hey there! Big fan of the extension and I was just wondering if contributions would be accepted (after being initially proposed, of course). For example I recently discovered that I could adjust playback speed on HTML5 videos by setting the `playbackRate` of a video element, and I was thinking of investigating adding that functionality to the extension.

**Comment by lrkissling** [comment]
Pull requests are certainly welcome! For new features I think it would be best to submit a feature proposal as an issue in github. Details on the look and feel would be highly appreciated, as would reference images to a similar implementation or mockup of what it will look like.

For this feature, keep in mind that Giant Bomb uses a variety of video players (Youtube, HTML5, Progressive, and whatever their live player is). I'm not sure if it's possible to control the playback rate on all of them, but the controls should not show up on unadjustable videos players.
