### ISSUE TITLE
e3motes

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#49]
`:massalex`
https://static.giantbomb.com/uploads/original/0/1992/3106236-3106227-massalexanimated.gif

`:cringe`
https://static.giantbomb.com/uploads/original/0/1992/3106237-3106225-bradcringesml3.png

**Comment by lrkissling** [comment]
`:maybe`
https://static.giantbomb.com/uploads/original/0/1992/3106238-3106226-maybe.png

**Comment by kmausolf** [comment]
I'll tackle this one this weekend.

**Comment by kmausolf** [comment]
Just kidding, I did it now so I wouldn't forget.

**Comment by lrkissling** [comment]
`:gooigi`
https://static.giantbomb.com/uploads/original/0/1992/3108107-gooigi.png
