### ISSUE TITLE
e(ye)motes

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#54]
`:eyes`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3117360-eyes.png

**Comment by lrkissling** [comment]
`:banana`
https://giantbomb1.cbsistatic.com/uploads-dev/original/0/1992/3122156-ezgif-4-ac5b09b2093c.gif

**Comment by lrkissling** [comment]
`:shoutout`
https://giantbomb1.cbsistatic.com/uploads-dev/original/0/1992/3121868-shoutout.png

**Comment by lrkissling** [comment]
`:benmoves`
https://giantbomb1.cbsistatic.com/uploads-dev/original/36/366200/3124094-benmoves.png

**Comment by lrkissling** [comment]
`:dp2`
https://giantbomb1.cbsistatic.com/uploads-dev/original/0/1992/3125374-ezgif-4-31e521fa6e20.gif

**Comment by bnrubin** [comment]
`:woooo`
https://giantbomb1.cbsistatic.com/uploads-dev/original/0/1992/3126907-ezgif-4-c4039e023ba9.gif

**Comment by bnrubin** [comment]
`:riki`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3127623-riki.png

**Comment by bnrubin** [comment]
`:kiki`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3127629-finalest.png

**Comment by lrkissling** [comment]
Completed for v4.5
