### ISSUE TITLE
Live show indicator not working

### ISSUE THREAD

**Issue by kmausolf** [lrkissling/giant-bomb-qol#56]
With the recent release of the QoL extension 4.5, the live show indicator is no longer working.

**Comment by kmausolf** [comment]
It seems to have activated about two hours late.  Not sure what's going on.

**Comment by lrkissling** [comment]
I noticed yesterday (before the update) that the indicator didn't light up in until well after the CoD stream started, as well. This might be an issue with the GB API. I am out of town so I might not be able to investigate this until Monday. If you want to check what the API is returning during a live stream, the endpoint we use is `https://www.giantbomb.com/api/chats/?api_key=[your key]`

If I recall correctly, the Infinite stream is always returned in this call, but if there's a live stream as well, it has always been the first result. So we'd want to verify that the endpoint returns the live stream, and that it's the first result.

**Comment by lrkissling** [comment]
The indicator lit up for Unprofessional Fridays, so I think it was just an API issue. However, it seems that the GBI icon is appearing for live streams as well. It was only supposed to be there for the GBI link.

**Comment by kmausolf** [comment]
Yeah, I think you're right.  It's working perfect on my end now.  Probably just an API hiccup.
