### ISSUE TITLE
All that we could do with this EMOTE-tion

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#57]
`:fish`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3128146-fish.jpg

`:jonno`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3128148-jonstopit.png

**Comment by lrkissling** [comment]
`:dietcoke`
https://giantbomb1.cbsistatic.com/uploads-dev/original/0/1992/3126905-ezgif-4-00cb78c3e625.gif

**Comment by kmausolf** [comment]
`:mugetsu`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3129312-mugetsufinal.png

**Comment by kmausolf** [comment]
`:mahardy`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3129321-mahardy.png

file under Duders

**Comment by kmausolf** [comment]
`:abbydance`
https://giantbomb1.cbsistatic.com/uploads-dev/original/9/95320/3126435-abbydancev01.gif

file under Popular
