### ISSUE TITLE
Auto-add new emotes to a 'New' section of the emotes tab.

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#59]
Adding emotes in a timely fashion is a pain! Users often go weeks without being able to select the hottest new 'motes!

We should see if we can automatically add new emotes to a 'New' section of the emotes tab. Once us intrepid and not-at-all-lazy developers get around to it, they can be sorted out of there and into the appropriate section via an update.

This 'New' or 'New Emotes' section should exist below the 'Popular' section. I think we should be able to find the complete list of emotes somewhere in the source of the page, but I wasn't able to find it with 5-10 minutes of looking. This whole idea sorta depends on my sincere belief that they are there!

If we can find such a parseable list, we simply have to loop through it and compare to the extension's list to find which ones are new. Add those to an otherwise empty 'New' section, which should be hidden from users if there are no emotes in it.

**Comment by kmausolf** [comment]
I believe all of the emote tag parsing happens on the server.  Might be difficult to access it directly, but perhaps we could ask that an emote list be added to the API?

**Comment by kmausolf** [comment]
Computron7000 of GBI chat says:

> the list is stored in the JS variable Phoenix.FireChat.Emotes but the code to access that has to run in the same context as the page and not a plugin

**Comment by lrkissling** [comment]
Sweet, thanks for investigating.

**Comment by lrkissling** [comment]
A Mozilla docs page on how we might be able to access the variable in our content script, though I'm not sure if this would work for Chrome.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#Accessing_page_script_objects_from_content_scripts

**Comment by lrkissling** [comment]
or maybe this if the above isn't Chrome-compatible...

https://intoli.com/blog/sandbox-breakout/
