### ISSUE TITLE
Little Orphan Emotes

### ISSUE THREAD

**Issue by lrkissling** [lrkissling/giant-bomb-qol#65]
`:annie`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3150160-annie.png

**Comment by lrkissling** [comment]
`:cchuck`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3151751-charliechuck.png

**Comment by lrkissling** [comment]
`:salty` was removed

**Comment by lrkissling** [comment]
`:benihana`
https://giantbomb1.cbsistatic.com/uploads/original/6/68646/3157731-benihana.png

**Comment by lrkissling** [comment]
`:suki`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3159312-suki.png

**Comment by kmausolf** [comment]
`:jollibee`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3146252-jollibee.png

**Comment by kmausolf** [comment]
`:minion`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3165291-minion.jpg

**Comment by kmausolf** [comment]
`:meesa`
https://giantbomb1.cbsistatic.com/uploads/original/36/366200/3162934-meesa.png
