### ISSUE TITLE
Feature Request: Disable Report Button Toggle

### ISSUE THREAD

**Issue by kmausolf** [lrkissling/giant-bomb-qol#69]
User Cynicologist on Giant Bomb requests a feature that allows the user to disable to report button on each chat post.

## Use Case
Cynicologist wants to reply to a post in the main chat.  As they are going to click the reply button, the chat moves, and they accidentally click the report button.  Frustrated by this, they turn on the "Disable Report Button" option in the QOL Addon settings.  When Cynicologist goes to reply to another post and the chat moves as they are clicking, the worst the mis-click can be is replying to the incorrect user.

**Comment by lrkissling** [comment]
Great work @han-sen ! Sorry for the delay on merging this, work kicked my butt and sapped my energy for hobby development for most of 2020.
